Repository Azure/LinuxPatchExtension, pull requests merged in 2025-04, with the labels that each got.

#293 Feature: Adding Azure Linux 3.0 Base Support
  src/core/src/bootstrap/ConfigurationFactory.py
  src/core/src/bootstrap/Constants.py
  src/core/src/bootstrap/EnvLayer.py
  src/core/src/core_logic/PatchAssessor.py
  src/core/src/package_managers/TdnfPackageManager.py
  src/core/src/package_managers/YumPackageManager.py
  src/core/src/package_managers/ZypperPackageManager.py
  src/core/tests/Test_CoreMain.py
  src/core/tests/Test_EnvLayer.py
  src/core/tests/Test_TdnfPackageManager.py
  src/core/tests/library/LegacyEnvLayerExtensions.py
Labels: enhancement

#306 Bugfix: Unit tests broken in Python 3.12
  src/core/tests/Test_CoreMain.py
  src/core/tests/Test_UbuntuProClient.py
  src/extension/tests/Test_ExtEnvHandler.py
Labels: bug, OE

#307 Coverage: Increase code coverage - TimerManager and ServiceManager
  src/core/tests/Test_ServiceManager.py
  src/core/tests/Test_TimerManager.py
Labels: engg. hygiene, OE

#311 Feature: Adding support for Azure Linux 2.0 in Tdnf Package Manager
  src/core/src/bootstrap/Constants.py
  src/core/src/bootstrap/EnvLayer.py
  src/core/src/package_managers/TdnfPackageManager.py
  src/core/tests/Test_EnvLayer.py
Labels: feature, OE

#308 Bugfix: Mitigate external Ubuntu Pro Client issues
  src/core/src/bootstrap/Constants.py
  src/core/src/package_managers/AptitudePackageManager.py
  src/core/src/package_managers/UbuntuProClient.py
  src/core/tests/Test_AptitudePackageManager.py
Labels: bug, OE

#310 Bugfix: Reboot Manager behavior - multiple bugfixes & error rate reduction
  src/core/src/bootstrap/Constants.py
  src/core/src/core_logic/PatchInstaller.py
  src/core/src/core_logic/RebootManager.py
  src/core/tests/Test_RebootManager.py
  src/core/tests/library/RuntimeCompositor.py
Labels: bug, OE
