Repository Azure/LinuxPatchExtension, pull requests merged in 2025-05, with the labels that each got.

#304 Clean-up: Envlayer dead-code clean-up for Environment Recorder and Emulator
  src/core/src/bootstrap/Bootstrapper.py
  src/core/src/bootstrap/ConfigurationFactory.py
  src/core/src/bootstrap/EnvLayer.py
  src/core/src/core_logic/ConfigurePatchingProcessor.py
  src/core/src/core_logic/PatchAssessor.py
  src/core/src/core_logic/PatchInstaller.py
  src/core/src/service_interfaces/StatusHandler.py
  src/core/src/service_interfaces/TelemetryWriter.py
  src/core/tests/Test_EnvLayer.py
  src/core/tests/library/LegacyEnvLayerExtensions.py
  src/core/tests/library/RuntimeCompositor.py
Labels: engg. hygiene, OE

#301 Bugfix: Restore patch mode config on Image Default
  src/core/src/core_logic/ConfigurePatchingProcessor.py
  src/core/src/package_managers/AptitudePackageManager.py
  src/core/src/package_managers/PackageManager.py
  src/core/src/package_managers/TdnfPackageManager.py
  src/core/src/package_managers/YumPackageManager.py
  src/core/src/package_managers/ZypperPackageManager.py
  src/core/tests/Test_AptitudePackageManager.py
  src/core/tests/Test_ConfigurePatchingProcessor.py
  src/core/tests/Test_TdnfPackageManager.py
  src/core/tests/Test_YumPackageManager.py
  src/core/tests/Test_ZypperPackageManager.py
  src/core/tests/library/LegacyEnvLayerExtensions.py
Labels: bug, OE

#315 Bugfix: Fix sudo check logs and wordings
  src/core/src/bootstrap/Bootstrapper.py
  src/core/src/bootstrap/Constants.py
  src/core/tests/Test_Bootstrapper.py
Labels: bug, engg. hygiene, OE

#325 Bugfix: Fixing Bootstrapper UT failure with Python 2.7
  src/core/tests/Test_Bootstrapper.py
Labels: bug, engg. hygiene
